### ISSUE TITLE
Unable to update pages in target if pages already exist

### ISSUE THREAD

**Issue by t-fulton** [internalfx/quickshot#43] opened 2017-05-02 17:33 UTC
I have two shopify environments, I'll call them A and B. I've transferred pages from A to B in the past. I've since added some pages to A and would like transfer all the pages to B (to get the new pages I added in A into B). However, I get the following error when I try the upload:
`{"handle":["has already been taken"]}`

Am I doing something wrong or is it not possible to do this? Do I have to delete all the pages from B first (that would be a bummer).

Thanks.

**Comment by MarioRicalde** [comment] 2017-07-06 02:34
As of right now - the current solution is to delete the pages from the target environment to ensure that the sync is good.

Also, from what I can tell collections are not kept.

**Comment by t-fulton** [comment] 2017-07-06 16:14
Unfortunately that also nukes the associated menus forcing you to recreate them. This fork addresses this issue nicely though https://github.com/kevinhaugen/quickshot-redux

**Comment by rickydazla** [comment] 2018-04-14 22:24
@t-fulton why don't you create a PR against this repo?

**Comment by rickydazla** [comment] 2018-04-14 22:40
Also FWIW this is a duplicate of #37

**Comment by internalfx** [comment] 2019-04-25 17:12
I'm closing this as quickshot has changed considerably.

**Closed as completed by internalfx** 2019-04-25 17:12 UTC
