### ISSUE TITLE
When doing a theme upload I get a 404 not found.

### ISSUE THREAD

**Issue by thsbrown** [internalfx/quickshot#40] opened 2016-09-14 03:35 UTC
I have downloaded a theme and i'm trying to push it to a different environment. Every time i do though I get the following error.

```
08:34:27 pm - Request Failed!: [404] Not Found

{"key":"theme/assets/ico-select.svg.liquid"}
```

Any clue why this could be happening?

Thank you in advance!

**Comment by RobWiddick** [comment] 2016-09-30 18:06
Same issue with v2.1.3 - I've even reset all targets and reinstalled QS... Private app permissions have full access. I think this is something in QS.

**Comment by rickydazla** [comment] 2018-04-14 22:40
This is a duplicate of #39

**Comment by internalfx** [comment] 2019-04-25 17:13
I'm closing this as quickshot has changed considerably.

**Closed as completed by internalfx** 2019-04-25 17:13 UTC
